### ISSUE TITLE
I got this error!

### ISSUE THREAD

**Issue by gilbertobitt** [sarfraznawaz2005/whatspup#6]
`Unhandled Rejection at: Promise Promise {
  <rejected> Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (C:\Users\Adiel\Downloads\whatspup-master\whatspup-master\node_modules\puppeteer\lib\FrameManager.js:695:58)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5) } reason: Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (C:\Users\Adiel\Downloads\whatspup-master\whatspup-master\node_modules\puppeteer\lib\FrameManager.js:695:58)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
`

**Comment by gilbertobitt** [comment]
i think occur becouse it didn't find the chat name! but i was thinking if i add a alternate way to chat when not find?? like update the contacts list and start chat with someone with the "title" name i input on the --chat command?

**Comment by sarfraznawaz2005** [comment]
Few suggestions:

- Make sure person you are trying to chat with is already visible in sidebar which means you have already initiated conversation with him/her because we use a selector to CLICK that name.
- Try using double quotes if that name contains space eg `--chat "My Contact"`
- We recently updated selector.js and chat.js files, make sure you use latest code

**Comment by gilbertobitt** [comment]
ok, i already did try someone i chat with but! i think will be amazing have a way to start a chat with some contact!
