### ISSUE TITLE
Initializing... 

### ISSUE THREAD

**Issue by alloanva** [sarfraznawaz2005/whatspup#8]
When run chat.js appear a message Initializing.. 
-open browser ok
-i scan the qr ok
- and return to console a seconds after appear a message.

╔══════════════╗
║                                    ║
║   Whatspup                 ║
║                                    ║
╚══════════════╝
Initializing...

Unhandled Rejection at: Promise Promise {
  <rejected> Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/home/al/Descargas/whatspup-master/node_modules/puppeteer/lib/FrameManager.js:789:58)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5) } reason: Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/home/al/Descargas/whatspup-master/node_modules/puppeteer/lib/FrameManager.js:789:58)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

**Comment by sarfraznawaz2005** [comment]
I cannot say why it doesn't work for you. I tested on my end on Windows 7 and 10 and it works, couple of suggestions:

- make sure you are using latest version. Try fresh installation in separate folder and then see.
- see if selectors (they are defined in selector.js file) used are matching with what you see for whatsapp web.

**Comment by alloanva** [comment]
I am using linux. appear error but when i click in left panel (list of users) works. My puppeteer version es 1.0.0

**Comment by sarfraznawaz2005** [comment]
yes, contact should already be visible in sidebar (conversation should already be started) for this to work because we use a selector to CLICK their name to continue chatting.
